In [16]:
from tensorflow.keras.preprocessing.text import one_hot 


In [17]:
##sentences

sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good'
      ]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
##Define the vocabulory size
voc_size=10000


In [20]:
##One Hot representation for every wordo

one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr



[[435, 8976, 9507, 7746],
 [435, 8976, 9507, 9845],
 [435, 7916, 9507, 6404],
 [8860, 5779, 5858, 8669, 5937],
 [8860, 5779, 5858, 8669, 888],
 [1720, 435, 9761, 9507, 2796],
 [9282, 130, 8698, 8669]]

In [21]:
##word embedding reoresentation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [22]:
import numpy as np

In [23]:
sent_length=8
embeded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embeded_docs)

[[   0    0    0    0  435 8976 9507 7746]
 [   0    0    0    0  435 8976 9507 9845]
 [   0    0    0    0  435 7916 9507 6404]
 [   0    0    0 8860 5779 5858 8669 5937]
 [   0    0    0 8860 5779 5858 8669  888]
 [   0    0    0 1720  435 9761 9507 2796]
 [   0    0    0    0 9282  130 8698 8669]]


In [24]:
##feature representation

dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.predict(embeded_docs)

1/1 [==============================] - 0s 58ms/step


array([[[ 4.0730510e-02, -9.3250163e-03, -4.6426941e-02, -4.2445838e-02,
         -1.7462242e-02, -3.5598755e-02,  2.3908641e-02,  1.0870956e-02,
          4.5124423e-02, -1.2448527e-02],
        [ 4.0730510e-02, -9.3250163e-03, -4.6426941e-02, -4.2445838e-02,
         -1.7462242e-02, -3.5598755e-02,  2.3908641e-02,  1.0870956e-02,
          4.5124423e-02, -1.2448527e-02],
        [ 4.0730510e-02, -9.3250163e-03, -4.6426941e-02, -4.2445838e-02,
         -1.7462242e-02, -3.5598755e-02,  2.3908641e-02,  1.0870956e-02,
          4.5124423e-02, -1.2448527e-02],
        [ 4.0730510e-02, -9.3250163e-03, -4.6426941e-02, -4.2445838e-02,
         -1.7462242e-02, -3.5598755e-02,  2.3908641e-02,  1.0870956e-02,
          4.5124423e-02, -1.2448527e-02],
        [-4.3618869e-02, -6.4935684e-03, -2.5428021e-02,  1.2306809e-02,
          3.9397765e-02,  3.6490295e-02, -1.6285241e-02, -3.6918152e-02,
         -2.7647842e-02,  3.1366833e-03],
        [-1.8028807e-02,  2.2521783e-02, -4.1337598e-02,  3.

In [27]:
embeded_docs[0]

array([   0,    0,    0,    0,  435, 8976, 9507, 7746])